Repository LJOSC/checkmark, pull requests merged in 2024-08, with the labels that each got.

#6 Redux setup
  .gitignore
  env.example
  package-lock.json
  package.json
  src/config.ts
  src/main.tsx
  src/redux/reducer.ts
  src/redux/slices/authSlice.ts
  src/redux/store.ts
  src/services/.gitkeep
  src/services/authApi.ts
  src/services/common.ts
  tsconfig.app.json
  vite.config.ts
Labels: enhancement, redux

#8 Sass setup
  README.md
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.tsx
  src/assets/styles/_mixins.scss
  src/assets/styles/_typography.scss
  src/assets/styles/_variables.scss
  src/assets/styles/main.scss
  tailwind.config.js
Labels: sass

#10 Boilerplate with sass and tailwind
  README.md
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.tsx
  src/assets/styles/main.scss
  tailwind.config.js
Labels: documentation

#12 add vscode extension recommendation
  .editorconfig
  .eslintrc.cjs
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: enhancement, good first issue
